apiVersion: v1alpha1
group: management
kind: ExternalSecret
name: musical-secret
metadata:
  scope:
    kind: Environment
    name: dxdemo
tags:
  - v1
spec:
  config:
    provider: Kubernetes
    name: ampgw-secret
    namespace: ampgw
  data:
    kind: TLS
    privateKeyAlias: listenerPrivateKey
    certificateAlias: listenerCertificate